### ISSUE TITLE
you forgot to include a default.png

### ISSUE THREAD

**Issue by delay** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#1]
I think you forgot to include a default.png for the profile pic. Which can cause a crash.  I think you need to add the image to your root folder in assets/images/default.png and include the asset in your pubspec.yaml.  

```  
flutter:
    assets:
        - assets/images/default.png
```

Anyway thanks for the great demo project, I am learning a lot from it!

**Comment by instamobile** [comment]
I've pushed a fix. Thanks for the report!
