### ISSUE TITLE
Create a User without a profile picture

### ISSUE THREAD

**Issue by wsciaroni** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#10]
## Background

It appears that when you create a user and don't provide a profile picture an exception is thrown.

## Steps to Recreate:

- Create an account WITHOUT a profile picture
- You will see the exception thrown in the debug terminal

The account will still have created successfully, but you will still receive the exception every time you launch the app afterwards (as the app is trying to pull an image from the url "" every time the app is launched)

## Expected behavior

If a profile picture is not provided, the default image for a profile picture should be used.

**Comment by mostafaAbdelazim** [comment]
This is not an actual issue, we leave the profile picture string empty, the CachedNetworkImage widget  fails to load the empty url (that's expected) and then prints that to the console, then loads the errorWidget which has the default image
