### ISSUE TITLE
Characters misspelled

### ISSUE THREAD

**Issue by wsciaroni** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#11]
https://github.com/instaflutter/flutter-login-screen-firebase-auth-facebook-login/blob/3af1a2e9860fb4373584f09e2c6ab3e5d19e59e8/lib/services/helper.dart#L32

**Comment by mostafaAbdelazim** [comment]
Thanks for your feedback, this type has been fixed in the latest commit.
