### ISSUE TITLE
KO

### ISSUE THREAD

**Issue by blondie63** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#12]
Hi, in this code there are some absolute reference to files
for example in AuthScreen.dart you have:
import 'file:///D:/FlutterFreebies2/FlutterLogin/lib/services/helper.dart';

you have to change to:
import '../../services/helper.dart';

**Comment by mostafaAbdelazim** [comment]
Thanks for your feedback, this issue was solved in the latest commit.
