### ISSUE TITLE
login with facebook error

### ISSUE THREAD

**Issue by Nishtha-Iwebservices** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#18]
when I tap on login with facebook, facebook dialog comes and suddenly dismiss and give error couldn't login with facebook.
Can you please let me know the error behind this?
I am getting the same in my project also.

**Comment by mostafaAbdelazim** [comment]
Hi, which platform are you experiencing this behavior on? Android, ios or both?

**Comment by mostafaAbdelazim** [comment]
Closing this as we can't reproduce the error, feel free to comment back with the reproduction steps and i'll reopen.
