### ISSUE TITLE
This app is using a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by ezspot** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#19]
"To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding."
Will you be able to fix this?

**Comment by To-Rex** [comment]
let me try too

**Comment by mostafaAbdelazim** [comment]
Thank you for your feedback, We've just pushed a new version, Let me know if you are still facing any issues.

**Comment by To-Rex** [comment]
thank you
