### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by VOIDCRUSHER** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#2]
Under what terms should this code be used? I would recommend adding a LICENSE file to make that clear.

**Comment by jangruenwaldt** [comment]
I was also going to say this. Adding a license file would be greatly appreciated. Thanks!

**Comment by mrcflorian** [comment]
It's MIT license guys, I'll update it when I get a chance. Cheers!
