### ISSUE TITLE
Not Issue (Query Related to Firebase)

### ISSUE THREAD

**Issue by RomeoDar** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#3]
I'm new in flutter programming, your project is awesome, great UI. my question is, can we integrate this project with our own firebase project ? i need to access phone number, photo and name of users. i need to add my own firebase project, so i could use more features of firebase (ads, push notification etc). how to add my own firebase project ? need help!

**Comment by mostafaAbdelazim** [comment]
This is the firebase guide on how to connect your app to firebase https://firebase.google.com/docs/flutter/setup ,
skip first step since you already have the flutter project created, make sure to have the same package/app ID in the flutter project (Android, iOS) and in your firebase app
