### ISSUE TITLE
Can't login, page keeps loading

### ISSUE THREAD

**Issue by andy34h** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#4]
Sign up works fine but when I try to log in the page just keeps loading and shows the message 'Logging in, please wait...' and never redirects to home page

**Comment by mehmetresatdemir** [comment]
child: TextFormField(
                              textAlignVertical: TextAlignVertical.center,
                              validator: validatePassword,
                              onSaved: (String val) {
                                email = val;
                              },
                              onFieldSubmitted: (password) async {
                                await onClick(_emailController.text, _passwordController.text);
                              },
                              controller : _passwordController,
                              textInputAction: TextInputAction.done,
                              style: TextStyle(fontSize: 18.0),

**Comment by arolihas** [comment]
Where is this snippet supposed to go? in onSaved you have email=val but it looks like this should be in the password part?

**Comment by mostafaAbdelazim** [comment]
This issue has been fixed
