### ISSUE TITLE
Query Related to Purple Splash Screen

### ISSUE THREAD

**Issue by MasiMasinga** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#5]
Fantastic source code this is. Currently experiencing issues in identifying and actually removing the purple splash screen and the rocket logo, can someone assist helping by pointing which .dart file is it in actually because I seem not to find be finding ?

**Comment by rajeshkulandaivel** [comment]
I do have the same question on the purple splash screen. Can you point to where it can be found?

**Comment by mostafaAbdelazim** [comment]
You gotta change it from native code, it's not part of the dart code.
 here's a helpful link: https://stackoverflow.com/questions/56583735/flutter-change-splash-screen-background-color
