### ISSUE TITLE
Absolute Paths Used in import

### ISSUE THREAD

**Issue by wsciaroni** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#8]
Hello,

After a quick look at your project, I was getting build errors.  I noticed that after replacing these lines with a relative import in the style the errors were corrected.

https://github.com/instaflutter/flutter-login-screen-firebase-auth-facebook-login/blob/3af1a2e9860fb4373584f09e2c6ab3e5d19e59e8/lib/main.dart#L11

Thank you,
W

**Comment by mostafaAbdelazim** [comment]
Thanks for pointing this out, my IDE sometimes does this local path import, it's now fixed

**Comment by wsciaroni** [comment]
Thanks for taking care of it! I appreciate all the work you've put in to this project.
